import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
  { path: 'getting-started', redirectTo: 'getting-started/angular', pathMatch: 'full' },
  { path: 'getting-started/angular', loadComponent: () => import('./pages/getting-started/getting-started.component').then(m => m.GettingStartedComponent) },
  { path: 'getting-started/react',   loadComponent: () => import('./pages/getting-started/getting-started.component').then(m => m.GettingStartedComponent) },
  { path: 'getting-started/html',    loadComponent: () => import('./pages/getting-started/getting-started.component').then(m => m.GettingStartedComponent) },
  { path: 'button',  loadComponent: () => import('./pages/button-page/button-page.component').then(m => m.ButtonPageComponent) },
  { path: 'card',    loadComponent: () => import('./pages/card-page/card-page.component').then(m => m.CardPageComponent) },
  { path: 'badge',   loadComponent: () => import('./pages/badge-page/badge-page.component').then(m => m.BadgePageComponent) },
  { path: 'modal',        loadComponent: () => import('./pages/modal-page/modal-page.component').then(m => m.ModalPageComponent) },
  { path: 'form-dialog',    loadComponent: () => import('./pages/form-dialog-page/form-dialog-page.component').then(m => m.FormDialogPageComponent) },
  { path: 'confirm-dialog', loadComponent: () => import('./pages/confirm-dialog-page/confirm-dialog-page.component').then(m => m.ConfirmDialogPageComponent) },
  { path: 'header',  loadComponent: () => import('./pages/header-page/header-page.component').then(m => m.HeaderPageComponent) },
  { path: 'icon',    loadComponent: () => import('./pages/icon-page/icon-page.component').then(m => m.IconPageComponent) },
  { path: 'tooltip', loadComponent: () => import('./pages/tooltip-page/tooltip-page.component').then(m => m.TooltipPageComponent) },
  { path: 'spinner',    loadComponent: () => import('./pages/spinner-page/spinner-page.component').then(m => m.SpinnerPageComponent) },
  { path: 'breadcrumb', loadComponent: () => import('./pages/breadcrumb-page/breadcrumb-page.component').then(m => m.BreadcrumbPageComponent) },
  { path: 'typography', loadComponent: () => import('./pages/typography-page/typography-page.component').then(m => m.TypographyPageComponent) },
  { path: 'input',     loadComponent: () => import('./pages/input-page/input-page.component').then(m => m.InputPageComponent) },
  { path: 'select',    loadComponent: () => import('./pages/select-page/select-page.component').then(m => m.SelectPageComponent) },
  { path: 'checkbox',  loadComponent: () => import('./pages/checkbox-page/checkbox-page.component').then(m => m.CheckboxPageComponent) },
  { path: 'radio',     loadComponent: () => import('./pages/radio-page/radio-page.component').then(m => m.RadioPageComponent) },
  { path: 'textarea',  loadComponent: () => import('./pages/textarea-page/textarea-page.component').then(m => m.TextareaPageComponent) },
  { path: 'switch',    loadComponent: () => import('./pages/switch-page/switch-page.component').then(m => m.SwitchPageComponent) },
  { path: 'search',   loadComponent: () => import('./pages/search-page/search-page.component').then(m => m.SearchPageComponent) },
  { path: 'filters',  loadComponent: () => import('./pages/filter-page/filter-page.component').then(m => m.FilterPageComponent) },
  { path: 'toast',    loadComponent: () => import('./pages/toast-page/toast-page.component').then(m => m.ToastPageComponent) },
  { path: 'sidebar',         loadComponent: () => import('./pages/sidebar-page/sidebar-page.component').then(m => m.SidebarPageComponent) },
  { path: 'solifi-sidebar',  loadComponent: () => import('./pages/solifi-sidebar-page/solifi-sidebar-page.component').then(m => m.SolifiSidebarPageComponent) },
  { path: 'app-shell', loadComponent: () => import('./pages/app-shell-page/app-shell-page.component').then(m => m.AppShellPageComponent) },
  {
    path: 'table',
    loadComponent: () => import('./pages/table-page/table-layout.component').then(m => m.TableLayoutComponent),
    children: [
      { path: '',          redirectTo: 'display', pathMatch: 'full' },
      { path: 'display',   loadComponent: () => import('./pages/table-page/display/table-display-page.component').then(m => m.TableDisplayPageComponent) },
      { path: 'data-grid', loadComponent: () => import('./pages/table-page/data-grid/table-data-grid-page.component').then(m => m.TableDataGridPageComponent) },
      { path: 'editable',  loadComponent: () => import('./pages/table-page/editable/table-editable-page.component').then(m => m.TableEditablePageComponent) },
    ]
  },
  { path: 'tabs',       loadComponent: () => import('./pages/tabs-page/tabs-page.component').then(m => m.TabsPageComponent) },
  { path: 'datepicker',    loadComponent: () => import('./pages/datepicker-page/datepicker-page.component').then(m => m.DatepickerPageComponent) },
  { path: 'multi-select', loadComponent: () => import('./pages/multiselect-page/multiselect-page.component').then(m => m.MultiSelectPageComponent) },
  { path: 'password-input', loadComponent: () => import('./pages/password-page/password-page.component').then(m => m.PasswordPageComponent) },
  // { path: 'combobox',     loadComponent: () => import('./pages/combobox-page/combobox-page.component').then(m => m.ComboboxPageComponent) },
  { path: 'skeleton',     loadComponent: () => import('./pages/skeleton-page/skeleton-page.component').then(m => m.SkeletonPageComponent) },
  { path: 'chip',         loadComponent: () => import('./pages/chip-page/chip-page.component').then(m => m.ChipPageComponent) },
  { path: 'tag',          loadComponent: () => import('./pages/tag-page/tag-page.component').then(m => m.TagPageComponent) },
  { path: 'list',         loadComponent: () => import('./pages/list-page/list-page.component').then(m => m.ListPageComponent) },
  { path: 'datagrid',     loadComponent: () => import('./pages/datagrid-page/datagrid-page.component').then(m => m.DataGridPageComponent) },
  { path: 'menu',         loadComponent: () => import('./pages/menu-page/menu-page.component').then(m => m.MenuPageComponent) },
  { path: 'faq',          loadComponent: () => import('./pages/faq-page/faq-page.component').then(m => m.FaqPageComponent) },
  { path: 'alert',        loadComponent: () => import('./pages/alert-page/alert-page.component').then(m => m.AlertPageComponent) },
  { path: 'pagination',   loadComponent: () => import('./pages/pagination-page/pagination-page.component').then(m => m.PaginationPageComponent) },
  { path: 'accordion',    loadComponent: () => import('./pages/accordion-page/accordion-page.component').then(m => m.AccordionPageComponent) },
];
