import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home.component').then(m => m.HomeComponent) },
  { path: 'getting-started', loadComponent: () => import('./pages/getting-started.component').then(m => m.GettingStartedComponent) },
  { path: 'button',  loadComponent: () => import('./pages/button-page.component').then(m => m.ButtonPageComponent) },
  { path: 'card',    loadComponent: () => import('./pages/card-page.component').then(m => m.CardPageComponent) },
  { path: 'badge',   loadComponent: () => import('./pages/badge-page.component').then(m => m.BadgePageComponent) },
  { path: 'modal',   loadComponent: () => import('./pages/modal-page.component').then(m => m.ModalPageComponent) },
  { path: 'header',  loadComponent: () => import('./pages/header-page.component').then(m => m.HeaderPageComponent) },
  { path: 'icon',    loadComponent: () => import('./pages/icon-page.component').then(m => m.IconPageComponent) },
  { path: 'tooltip', loadComponent: () => import('./pages/tooltip-page.component').then(m => m.TooltipPageComponent) },
  { path: 'spinner',    loadComponent: () => import('./pages/spinner-page.component').then(m => m.SpinnerPageComponent) },
  { path: 'breadcrumb', loadComponent: () => import('./pages/breadcrumb-page.component').then(m => m.BreadcrumbPageComponent) },
  { path: 'typography', loadComponent: () => import('./pages/typography-page.component').then(m => m.TypographyPageComponent) },
  { path: 'input',     loadComponent: () => import('./pages/input-page.component').then(m => m.InputPageComponent) },
  { path: 'select',    loadComponent: () => import('./pages/select-page.component').then(m => m.SelectPageComponent) },
  { path: 'checkbox',  loadComponent: () => import('./pages/checkbox-page.component').then(m => m.CheckboxPageComponent) },
  { path: 'radio',     loadComponent: () => import('./pages/radio-page.component').then(m => m.RadioPageComponent) },
  { path: 'textarea',  loadComponent: () => import('./pages/textarea-page.component').then(m => m.TextareaPageComponent) },
  { path: 'switch',    loadComponent: () => import('./pages/switch-page.component').then(m => m.SwitchPageComponent) },
  { path: 'search',   loadComponent: () => import('./pages/search-page.component').then(m => m.SearchPageComponent) },
  { path: 'filters',  loadComponent: () => import('./pages/filter-page.component').then(m => m.FilterPageComponent) },
  { path: 'toast',    loadComponent: () => import('./pages/toast-page.component').then(m => m.ToastPageComponent) },
  { path: 'sidebar',   loadComponent: () => import('./pages/sidebar-page.component').then(m => m.SidebarPageComponent) },
  { path: 'app-shell', loadComponent: () => import('./pages/app-shell-page.component').then(m => m.AppShellPageComponent) },
];
